# -*- mode: ruby -*-
# vi: set ft=ruby :

#plugins
required_plugins = %w(vagrant-proxyconf)
# Could add vagrant cachier? Less of a problem at JQ but no harm in having it anyway?

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/centos7"
  #config.ssh.insert_key = false

  #plugin vagrant-proxyconf
  config.proxy.http     = "http://jos-repo-server.datacom.co.nz:3128/"
  config.proxy.https    = "http://jos-repo-server.datacom.co.nz:3128/"
  config.proxy.no_proxy = "localhost,127.0.0.1,.datacom.co.nz" # this should match hosts file

  config.vm.provider :virtualbox do |v|
    v.name = "gitlab"
    v.memory = 2048
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.hostname = "gitlab"
  config.vm.network :private_network, ip: "192.168.33.22"

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :gitlab do |gitlab|
  end

  # Ansible provisioner.
  config.vm.provision "ansible_local" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.inventory_path = "provisioning/inventory"
    ansible.galaxy_role_file = "requirements.yml"
    ansible.become = true
  end

end
